# Generated by Django 3.1.1 on 2020-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='result',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='history',
            name='keyword',
            field=models.CharField(default='', max_length=512),
        ),
    ]
